// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package index_manager

import (
	"context"

	"github.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/services/index_manager/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIndexManager creates a new instance of MockIndexManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexManager {
	mock := &MockIndexManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexManager is an autogenerated mock type for the IndexManager type
type MockIndexManager struct {
	mock.Mock
}

type MockIndexManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexManager) EXPECT() *MockIndexManager_Expecter {
	return &MockIndexManager_Expecter{mock: &_m.Mock}
}

// AutoSync provides a mock function for the type MockIndexManager
func (_mock *MockIndexManager) AutoSync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AutoSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexManager_AutoSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoSync'
type MockIndexManager_AutoSync_Call struct {
	*mock.Call
}

// AutoSync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexManager_Expecter) AutoSync(ctx any) *MockIndexManager_AutoSync_Call {
	return &MockIndexManager_AutoSync_Call{Call: _e.mock.On("AutoSync", ctx)}
}

func (_c *MockIndexManager_AutoSync_Call) Run(run func(ctx context.Context)) *MockIndexManager_AutoSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexManager_AutoSync_Call) Return(err error) *MockIndexManager_AutoSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexManager_AutoSync_Call) RunAndReturn(run func(ctx context.Context) error) *MockIndexManager_AutoSync_Call {
	_c.Call.Return(run)
	return _c
}

// GetVectorIndex provides a mock function for the type MockIndexManager
func (_mock *MockIndexManager) GetVectorIndex() *dto.VectorIndex {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVectorIndex")
	}

	var r0 *dto.VectorIndex
	if returnFunc, ok := ret.Get(0).(func() *dto.VectorIndex); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VectorIndex)
		}
	}
	return r0
}

// MockIndexManager_GetVectorIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVectorIndex'
type MockIndexManager_GetVectorIndex_Call struct {
	*mock.Call
}

// GetVectorIndex is a helper method to define mock.On call
func (_e *MockIndexManager_Expecter) GetVectorIndex() *MockIndexManager_GetVectorIndex_Call {
	return &MockIndexManager_GetVectorIndex_Call{Call: _e.mock.On("GetVectorIndex")}
}

func (_c *MockIndexManager_GetVectorIndex_Call) Run(run func()) *MockIndexManager_GetVectorIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexManager_GetVectorIndex_Call) Return(vectorIndex *dto.VectorIndex) *MockIndexManager_GetVectorIndex_Call {
	_c.Call.Return(vectorIndex)
	return _c
}

func (_c *MockIndexManager_GetVectorIndex_Call) RunAndReturn(run func() *dto.VectorIndex) *MockIndexManager_GetVectorIndex_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockIndexManager
func (_mock *MockIndexManager) Sync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexManager_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockIndexManager_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIndexManager_Expecter) Sync(ctx any) *MockIndexManager_Sync_Call {
	return &MockIndexManager_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockIndexManager_Sync_Call) Run(run func(ctx context.Context)) *MockIndexManager_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexManager_Sync_Call) Return(err error) *MockIndexManager_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexManager_Sync_Call) RunAndReturn(run func(ctx context.Context) error) *MockIndexManager_Sync_Call {
	_c.Call.Return(run)
	return _c
}
