// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

// BaseResponse Internal Server Error
type BaseResponse struct {
	// Message A human-readable message describing the error.
	Message string `json:"message"`
	Ok      bool   `json:"ok"`
}

// AskParams defines parameters for Ask.
type AskParams struct {
	// Query Query that user asked.
	Query string `form:"query" json:"query"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Ask.
	// (GET /ask)
	Ask(
		w http.ResponseWriter,
		r *http.Request,
		params AskParams,
	)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Ask operation middleware
func (siw *ServerInterfaceWrapper) Ask(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AskParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ask(
			w,
			r,
			params,
		)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL            string
	BaseRouter         *mux.Router
	Middlewares        []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
	RequestMiddlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(
		options.BaseURL+"/ask",
		prepareHandler(http.HandlerFunc(wrapper.Ask), "/ask", options).(http.HandlerFunc),
	).Methods("GET")

	return r
}

func prepareHandler(h http.Handler, path string, opts GorillaServerOptions) http.Handler {
	h = otelhttp.WithRouteTag(opts.BaseURL+path, h).(http.HandlerFunc)

	for _, middleware := range opts.RequestMiddlewares {
		h = middleware(h)
	}

	return h
}

// SSEWriter helps writing Server-Sent Events responses.
type SSEWriter struct {
	w       http.ResponseWriter
	flusher http.Flusher
}

// NewSSEWriter configures the response as an SSE stream.
func NewSSEWriter(
	w http.ResponseWriter,
) (*SSEWriter, error) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		return nil, errors.New("streaming unsupported")
	}

	headers := w.Header()

	headers.Set(
		"Content-Type",
		"text/event-stream",
	)

	headers.Set(
		"Cache-Control",
		"no-cache",
	)

	headers.Set(
		"Connection",
		"keep-alive",
	)

	return &SSEWriter{
		w:       w,
		flusher: flusher,
	}, nil
}

// Send writes a standard SSE message:
//
//	data: {...}
func (s *SSEWriter) Send(v any) error {
	payload, err := json.Marshal(v)
	if err != nil {
		return err
	}

	_, err = fmt.Fprintf(
		s.w,
		"data: %s\n\n",
		payload,
	)

	if err != nil {
		return err
	}

	s.flusher.Flush()

	return nil
}

// SendEvent writes a named SSE event:
//
//	event: token
//	data: {...}
func (s *SSEWriter) SendEvent(
	event string,
	v any,
) error {
	payload, err := json.Marshal(v)
	if err != nil {
		return err
	}

	_, err = fmt.Fprintf(
		s.w,
		"event: %s\n",
		event,
	)

	if err != nil {
		return err
	}

	_, err = fmt.Fprintf(
		s.w,
		"data: %s\n\n",
		payload,
	)

	if err != nil {
		return err
	}

	s.flusher.Flush()

	return nil
}

// Comment writes an SSE comment:
//
//	: keepalive
func (s *SSEWriter) Comment(
	comment string,
) error {
	_, err := fmt.Fprintf(
		s.w,
		": %s\n\n",
		comment,
	)

	if err != nil {
		return err
	}

	s.flusher.Flush()

	return nil
}

// Retry instructs the client how long to wait before reconnecting.
func (s *SSEWriter) Retry(
	duration time.Duration,
) error {
	_, err := fmt.Fprintf(
		s.w,
		"retry: %d\n\n",
		duration.Milliseconds(),
	)

	if err != nil {
		return err
	}

	s.flusher.Flush()

	return nil
}

// Done sends the OpenAI-style stream terminator:
//
//	data: [DONE]
func (s *SSEWriter) Done() error {
	_, err := fmt.Fprint(
		s.w,
		"data: [DONE]\n\n",
	)

	if err != nil {
		return err
	}

	s.flusher.Flush()

	return nil
}
