// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package embedding

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddingService creates a new instance of MockEmbeddingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingService {
	mock := &MockEmbeddingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingService is an autogenerated mock type for the EmbeddingService type
type MockEmbeddingService struct {
	mock.Mock
}

type MockEmbeddingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingService) EXPECT() *MockEmbeddingService_Expecter {
	return &MockEmbeddingService_Expecter{mock: &_m.Mock}
}

// Embedding provides a mock function for the type MockEmbeddingService
func (_mock *MockEmbeddingService) Embedding(ctx context.Context, text string) ([]float32, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Embedding")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingService_Embedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embedding'
type MockEmbeddingService_Embedding_Call struct {
	*mock.Call
}

// Embedding is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockEmbeddingService_Expecter) Embedding(ctx any, text any) *MockEmbeddingService_Embedding_Call {
	return &MockEmbeddingService_Embedding_Call{Call: _e.mock.On("Embedding", ctx, text)}
}

func (_c *MockEmbeddingService_Embedding_Call) Run(run func(ctx context.Context, text string)) *MockEmbeddingService_Embedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingService_Embedding_Call) Return(float32s []float32, err error) *MockEmbeddingService_Embedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockEmbeddingService_Embedding_Call) RunAndReturn(run func(ctx context.Context, text string) ([]float32, error)) *MockEmbeddingService_Embedding_Call {
	_c.Call.Return(run)
	return _c
}
