// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chunker

import (
	"context"

	"github.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/contracts/chunker/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockChunkerServiceClient creates a new instance of MockChunkerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkerServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkerServiceClient {
	mock := &MockChunkerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChunkerServiceClient is an autogenerated mock type for the ChunkerServiceClient type
type MockChunkerServiceClient struct {
	mock.Mock
}

type MockChunkerServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunkerServiceClient) EXPECT() *MockChunkerServiceClient_Expecter {
	return &MockChunkerServiceClient_Expecter{mock: &_m.Mock}
}

// ExtractChunks provides a mock function for the type MockChunkerServiceClient
func (_mock *MockChunkerServiceClient) ExtractChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExtractChunks")
	}

	var r0 grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse], error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse]); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChunkerServiceClient_ExtractChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractChunks'
type MockChunkerServiceClient_ExtractChunks_Call struct {
	*mock.Call
}

// ExtractChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockChunkerServiceClient_Expecter) ExtractChunks(ctx any, opts ...any) *MockChunkerServiceClient_ExtractChunks_Call {
	return &MockChunkerServiceClient_ExtractChunks_Call{Call: _e.mock.On("ExtractChunks",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockChunkerServiceClient_ExtractChunks_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockChunkerServiceClient_ExtractChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 1 {
			variadicArgs = args[1].([]grpc.CallOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChunkerServiceClient_ExtractChunks_Call) Return(bidiStreamingClient grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse], err error) *MockChunkerServiceClient_ExtractChunks_Call {
	_c.Call.Return(bidiStreamingClient, err)
	return _c
}

func (_c *MockChunkerServiceClient_ExtractChunks_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[chunker.ChunkRequest, chunker.ChunkResponse], error)) *MockChunkerServiceClient_ExtractChunks_Call {
	_c.Call.Return(run)
	return _c
}
