// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package search

import (
	"context"

	"github.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/contracts/public/v1/openapi"
	"github.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/services/search/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchService creates a new instance of MockSearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchService {
	mock := &MockSearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchService is an autogenerated mock type for the SearchService type
type MockSearchService struct {
	mock.Mock
}

type MockSearchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchService) EXPECT() *MockSearchService_Expecter {
	return &MockSearchService_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockSearchService
func (_mock *MockSearchService) Search(ctx context.Context, query string) ([]dto.SearchResult, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []dto.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]dto.SearchResult, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []dto.SearchResult); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearchService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockSearchService_Expecter) Search(ctx any, query any) *MockSearchService_Search_Call {
	return &MockSearchService_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockSearchService_Search_Call) Run(run func(ctx context.Context, query string)) *MockSearchService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchService_Search_Call) Return(searchResults []dto.SearchResult, err error) *MockSearchService_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockSearchService_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]dto.SearchResult, error)) *MockSearchService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDocuments provides a mock function for the type MockSearchService
func (_mock *MockSearchService) SearchDocuments(ctx context.Context, query string) ([]dto.SearchResult, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchDocuments")
	}

	var r0 []dto.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]dto.SearchResult, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []dto.SearchResult); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchService_SearchDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDocuments'
type MockSearchService_SearchDocuments_Call struct {
	*mock.Call
}

// SearchDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockSearchService_Expecter) SearchDocuments(ctx any, query any) *MockSearchService_SearchDocuments_Call {
	return &MockSearchService_SearchDocuments_Call{Call: _e.mock.On("SearchDocuments", ctx, query)}
}

func (_c *MockSearchService_SearchDocuments_Call) Run(run func(ctx context.Context, query string)) *MockSearchService_SearchDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchService_SearchDocuments_Call) Return(searchResults []dto.SearchResult, err error) *MockSearchService_SearchDocuments_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockSearchService_SearchDocuments_Call) RunAndReturn(run func(ctx context.Context, query string) ([]dto.SearchResult, error)) *MockSearchService_SearchDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// SearchHandler provides a mock function for the type MockSearchService
func (_mock *MockSearchService) SearchHandler() api.SearchHandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SearchHandler")
	}

	var r0 api.SearchHandlerFunc
	if returnFunc, ok := ret.Get(0).(func() api.SearchHandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.SearchHandlerFunc)
		}
	}
	return r0
}

// MockSearchService_SearchHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchHandler'
type MockSearchService_SearchHandler_Call struct {
	*mock.Call
}

// SearchHandler is a helper method to define mock.On call
func (_e *MockSearchService_Expecter) SearchHandler() *MockSearchService_SearchHandler_Call {
	return &MockSearchService_SearchHandler_Call{Call: _e.mock.On("SearchHandler")}
}

func (_c *MockSearchService_SearchHandler_Call) Run(run func()) *MockSearchService_SearchHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSearchService_SearchHandler_Call) Return(searchHandlerFunc api.SearchHandlerFunc) *MockSearchService_SearchHandler_Call {
	_c.Call.Return(searchHandlerFunc)
	return _c
}

func (_c *MockSearchService_SearchHandler_Call) RunAndReturn(run func() api.SearchHandlerFunc) *MockSearchService_SearchHandler_Call {
	_c.Call.Return(run)
	return _c
}
