// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BaseResponse Internal Server Error
type BaseResponse struct {
	// Message A human-readable message describing the error.
	Message string `json:"message"`
	Ok      bool   `json:"ok"`
}

// DocumentUploadRequest defines model for DocumentUploadRequest.
type DocumentUploadRequest struct {
	// Document Document to upload.
	Document openapi_types.File `json:"document"`
}

// DocumentUploadResponse defines model for DocumentUploadResponse.
type DocumentUploadResponse struct {
	// ChunksAmount Amount of uploaded chunks.
	ChunksAmount int64 `json:"chunksAmount"`

	// FileName Name of the uploaded file.
	FileName string `json:"fileName"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Content Content of the chunk
	Content string `json:"content"`

	// CosineSimilarity Cosine similarity.
	CosineSimilarity float64 `json:"cosineSimilarity"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	// Query Query to look for.
	Query string `form:"query" json:"query"`
}

// DocumentUploadMultipartRequestBody defines body for DocumentUpload for multipart/form-data ContentType.
type DocumentUploadMultipartRequestBody = DocumentUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload document.
	// (POST /documents/upload)
	DocumentUpload(w http.ResponseWriter, r *http.Request)
	// Search.
	// (GET /search)
	Search(w http.ResponseWriter, r *http.Request, params SearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DocumentUpload operation middleware
func (siw *ServerInterfaceWrapper) DocumentUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DocumentUpload(w, r)
	}))

	// Apply operation timeout (default 5000 ms, can be overridden by x-timeout)
	{
		timeoutMs := int64(5000)

		if v := int64(20000); v > 0 {
			timeoutMs = v
		}

		if timeoutMs > 0 {
			timeoutDuration := time.Duration(timeoutMs) * time.Millisecond
			var cancel context.CancelFunc
			ctx, cancel = context.WithTimeout(ctx, timeoutDuration)
			defer cancel()
		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Search(w, r, params)
	}))

	// Apply operation timeout (default 5000 ms, can be overridden by x-timeout)
	{
		timeoutMs := int64(5000)

		if v := int64(5000); v > 0 {
			timeoutMs = v
		}

		if timeoutMs > 0 {
			timeoutDuration := time.Duration(timeoutMs) * time.Millisecond
			var cancel context.CancelFunc
			ctx, cancel = context.WithTimeout(ctx, timeoutDuration)
			defer cancel()
		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL            string
	BaseRouter         *mux.Router
	Middlewares        []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
	RequestMiddlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(
		options.BaseURL+"/documents/upload",
		prepareHandler(http.HandlerFunc(wrapper.DocumentUpload), "/documents/upload", options).(http.HandlerFunc),
	).Methods("POST")

	r.HandleFunc(
		options.BaseURL+"/search",
		prepareHandler(http.HandlerFunc(wrapper.Search), "/search", options).(http.HandlerFunc),
	).Methods("GET")

	return r
}

func prepareHandler(h http.Handler, path string, opts GorillaServerOptions) http.Handler {
	h = otelhttp.WithRouteTag(opts.BaseURL+path, h).(http.HandlerFunc)

	for _, middleware := range opts.RequestMiddlewares {
		h = middleware(h)
	}

	return h
}

type (
	// (POST /documents/upload)
	DocumentUploadHandlerFunc func(ctx context.Context, request DocumentUploadRequestObject) (DocumentUploadResponseObject, error)
	// (GET /search)
	SearchHandlerFunc func(ctx context.Context, request SearchRequestObject) (SearchResponseObject, error)
)

type StrictServer struct {
	// (POST /documents/upload)
	DocumentUploadHandler DocumentUploadHandlerFunc
	// (GET /search)
	SearchHandler SearchHandlerFunc
}

// (POST /documents/upload)
func (s StrictServer) DocumentUpload(ctx context.Context, request DocumentUploadRequestObject) (DocumentUploadResponseObject, error) {
	if s.DocumentUploadHandler == nil {
		return nil, errors.New("implement me")
	}

	return s.DocumentUploadHandler(ctx, request)
}

// (GET /search)
func (s StrictServer) Search(ctx context.Context, request SearchRequestObject) (SearchResponseObject, error) {
	if s.SearchHandler == nil {
		return nil, errors.New("implement me")
	}

	return s.SearchHandler(ctx, request)
}

type DocumentUploadRequestObject struct {
	Body *multipart.Reader
}

type DocumentUploadResponseObject interface {
	VisitDocumentUploadResponse(w http.ResponseWriter) error
}

type DocumentUpload200JSONResponse DocumentUploadResponse

func (response DocumentUpload200JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DocumentUpload400JSONResponse BaseResponse

func (response DocumentUpload400JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DocumentUpload401JSONResponse BaseResponse

func (response DocumentUpload401JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DocumentUpload403JSONResponse BaseResponse

func (response DocumentUpload403JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DocumentUpload404JSONResponse BaseResponse

func (response DocumentUpload404JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DocumentUpload500JSONResponse BaseResponse

func (response DocumentUpload500JSONResponse) VisitDocumentUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchRequestObject struct {
	Params SearchParams
}

type SearchResponseObject interface {
	VisitSearchResponse(w http.ResponseWriter) error
}

type Search200JSONResponse SearchResponse

func (response Search200JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Search400JSONResponse BaseResponse

func (response Search400JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Search401JSONResponse BaseResponse

func (response Search401JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Search403JSONResponse BaseResponse

func (response Search403JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Search404JSONResponse BaseResponse

func (response Search404JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type Search500JSONResponse BaseResponse

func (response Search500JSONResponse) VisitSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Upload document.
	// (POST /documents/upload)
	DocumentUpload(ctx context.Context, request DocumentUploadRequestObject) (DocumentUploadResponseObject, error)
	// Search.
	// (GET /search)
	Search(ctx context.Context, request SearchRequestObject) (SearchResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DocumentUpload operation middleware
func (sh *strictHandler) DocumentUpload(w http.ResponseWriter, r *http.Request) {
	var request DocumentUploadRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DocumentUpload(ctx, request.(DocumentUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DocumentUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DocumentUploadResponseObject); ok {
		if err := validResponse.VisitDocumentUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Search operation middleware
func (sh *strictHandler) Search(w http.ResponseWriter, r *http.Request, params SearchParams) {
	var request SearchRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Search(ctx, request.(SearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Search")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchResponseObject); ok {
		if err := validResponse.VisitSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
