# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/chunker.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/chunker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v1/chunker.proto\x12\nchunker.v1\"b\n\x0c\x43hunkRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\x12\x15\n\rchunk_overlap\x18\x04 \x01(\x05\"?\n\rChunkResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\t2Z\n\x0e\x43hunkerService\x12H\n\rExtractChunks\x12\x18.chunker.v1.ChunkRequest\x1a\x19.chunker.v1.ChunkResponse(\x01\x30\x01\x42XZVgithub.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/contracts/chunkerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.chunker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/evgeniyprivalov/ai-vector-embedding/backend/core/internal/contracts/chunker'
  _globals['_CHUNKREQUEST']._serialized_start=32
  _globals['_CHUNKREQUEST']._serialized_end=130
  _globals['_CHUNKRESPONSE']._serialized_start=132
  _globals['_CHUNKRESPONSE']._serialized_end=195
  _globals['_CHUNKERSERVICE']._serialized_start=197
  _globals['_CHUNKERSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
